'use client';

import { useMemo, useState } from 'react';
import {
  Bot,
  Check,
  Circle,
  Clock3,
  PencilLine,
  RotateCcw,
  Send,
  Sparkles,
  X,
} from 'lucide-react';

type TabFilter = 'All' | 'Lessons' | 'Questions' | 'Pending' | 'Approved' | 'Rejected';

type QueueItem = {
  id: number;
  type: 'Lesson' | 'Questions';
  title: string;
  subtitle: string;
  meta: string;
  status: 'Pending' | 'Approved' | 'Rejected';
  badgeColor: string;
};

const queueItems: QueueItem[] = [
  {
    id: 1,
    type: 'Lesson',
    title: 'Interfaces — full lesson draft',
    subtitle: 'OOP in C# • 35m ago',
    meta: '3m ago',
    status: 'Pending',
    badgeColor: 'bg-rose-500/15 text-rose-600',
  },
  {
    id: 2,
    type: 'Questions',
    title: '12 questions on polymorphism',
    subtitle: 'OOP in C# • 1h ago',
    meta: '1h ago',
    status: 'Pending',
    badgeColor: 'bg-rose-500/15 text-rose-600',
  },
  {
    id: 3,
    type: 'Lesson',
    title: 'for / while / foreach lesson',
    subtitle: 'C# Fundamentals • 3h ago',
    meta: '3h ago',
    status: 'Pending',
    badgeColor: 'bg-rose-500/15 text-rose-600',
  },
  {
    id: 4,
    type: 'Questions',
    title: '8 questions on async/await',
    subtitle: 'Advanced C# • Yesterday',
    meta: 'Yesterday',
    status: 'Pending',
    badgeColor: 'bg-rose-500/15 text-rose-600',
  },
];

const tabs: TabFilter[] = ['All', 'Lessons', 'Questions', 'Pending', 'Approved', 'Rejected'];

export default function AIReviewQueuePage() {
  const [activeTab, setActiveTab] = useState<TabFilter>('Pending');
  const [selectedId, setSelectedId] = useState<number>(1);

  const filteredItems = useMemo(() => {
    if (activeTab === 'All') return queueItems;
    if (activeTab === 'Lessons') return queueItems.filter((item) => item.type === 'Lesson');
    if (activeTab === 'Questions') return queueItems.filter((item) => item.type === 'Questions');
    return queueItems.filter((item) => item.status === activeTab);
  }, [activeTab]);

  const selectedItem =
    filteredItems.find((item) => item.id === selectedId) ?? filteredItems[0] ?? queueItems[0];

  return (
    <div className="mx-auto max-w-[1500px] space-y-6">
      <div className="flex items-center gap-3">
        <span className="inline-flex items-center gap-2 rounded-md border border-cyan-200/60 bg-cyan-50 px-2.5 py-1 text-xs font-semibold text-cyan-700">
          <Sparkles className="h-3.5 w-3.5" />
          AI assisted
        </span>
      </div>

      <div className="space-y-2">
        <h1 className="text-3xl font-bold tracking-tight text-[#002C3E] sm:text-4xl">AI Content Review</h1>
        <p className="text-base text-[#637981]">
          Nothing generated by AI reaches students without a human decision.
        </p>
      </div>

      <div className="rounded-2xl border border-[#dfe6df] bg-[#f3f7f5] p-1.5 shadow-xs">
        <div className="flex flex-wrap gap-2">
          {tabs.map((tab) => {
            const isActive = activeTab === tab;
            return (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                className={[
                  'rounded-xl px-4 py-2 text-sm font-medium transition',
                  isActive
                    ? 'bg-white text-[#002C3E] shadow-xs ring-1 ring-[#dfe6df] font-semibold'
                    : 'text-[#637981] hover:text-[#002C3E] hover:bg-white/50',
                ].join(' ')}
              >
                {tab}
              </button>
            );
          })}
        </div>
      </div>

      <div className="grid gap-6 xl:grid-cols-[0.88fr_1.7fr_0.85fr]">
        <aside className="min-w-0 rounded-2xl border border-[#dfe6df] bg-white p-4 shadow-xs">
          <div className="mb-4 flex items-center justify-between">
            <h2 className="text-[18px] font-bold text-[#002C3E]">Queue</h2>
            <span className="text-sm text-[#637981]">{filteredItems.length} items pending</span>
          </div>

          <div className="space-y-3">
            {filteredItems.map((item) => {
              const selected = selectedItem.id === item.id;
              return (
                <button
                  key={item.id}
                  onClick={() => setSelectedId(item.id)}
                  className={[
                    'w-full rounded-2xl border p-3 text-left transition',
                    selected ? 'border-[#F7444E]/40 bg-[#F7444E]/10 text-[#002C3E]' : 'border-[#dfe6df] bg-white hover:bg-[#f3f7f5] text-[#002C3E]',
                  ].join(' ')}
                >
                  <div className="flex items-center gap-2 text-[#637981]">
                    <span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-[11px] font-medium ${item.badgeColor}`}>
                      <Sparkles className="h-3 w-3" />
                      {item.type}
                    </span>
                  </div>

                  <h3 className="mt-3 text-[17px] font-semibold leading-6 text-[#002C3E]">{item.title}</h3>
                  <p className="mt-2 text-sm text-[#637981]">{item.subtitle}</p>
                </button>
              );
            })}
          </div>
        </aside>

        <main className="min-w-0 rounded-2xl border border-[#dfe6df] bg-white p-4 shadow-xs">
          <div className="mb-4 flex items-center justify-between gap-3 rounded-2xl border border-[#dfe6df] bg-[#fbfcf8] px-3 py-2.5">
            <div className="flex items-center gap-2 text-[#002C3E]">
              <span className="inline-flex items-center rounded-full bg-rose-500/15 px-2.5 py-1 text-[11px] font-semibold text-rose-600">
                <Sparkles className="mr-1 h-3 w-3" />
                Lesson
              </span>
            </div>

            <button className="inline-flex items-center gap-2 rounded-full border border-[#dfe6df] bg-white px-3 py-1.5 text-xs font-medium text-[#002C3E]">
              <Clock3 className="h-3.5 w-3.5 text-amber-500" />
              In review
            </button>
          </div>

          <div className="space-y-5">
            <h2 className="text-[28px] font-bold leading-tight tracking-[-0.04em] text-[#002C3E]">
              Encapsulation in Practice
            </h2>

            <p className="text-base leading-7 text-[#637981]">
              Encapsulation is the OOP principle of hiding internal state and exposing behaviour through a controlled public surface. In C# you achieve it with access modifiers, properties and validation inside methods.
            </p>

            <div className="overflow-hidden rounded-2xl border border-slate-700 bg-[#021926] shadow-inner">
              <div className="flex items-center gap-2 border-b border-slate-700 bg-[#021a2a] px-4 py-2 text-[11px] text-slate-300">
                <span className="h-2.5 w-2.5 rounded-full bg-[#ff5f57]" />
                <span className="h-2.5 w-2.5 rounded-full bg-[#febc2e]" />
                <span className="h-2.5 w-2.5 rounded-full bg-[#28c840]" />
                <span className="ml-3 font-mono text-slate-400">Student.cs</span>
              </div>

              <pre className="overflow-x-auto p-4 font-mono text-[14px] leading-7 text-slate-100">
                <code>{`public class Student
{
    public string Name { get; set; }
    public int Credits { get; private set; }

    public Student(string name) => Name = name;

    public void Enroll(int credits)
    {
        if (credits <= 0)
            throw new ArgumentOutOfRangeException(nameof(credits));

        Credits += credits;
    }

    public void Introduce()
    {
        Console.WriteLine($"Hello, {Name}");
    }
}`}</code>
              </pre>
            </div>

            <div className="rounded-2xl border border-rose-200/60 bg-rose-50/70 px-5 py-4 text-[18px] font-semibold leading-8 text-rose-800">
              Rule of thumb: a class should never let external code put it into an invalid state. If a value has rules, it belongs behind a property or a method.
            </div>
          </div>
        </main>

        <aside className="min-w-0 space-y-5">
          <div className="rounded-2xl border border-[#dfe6df] bg-white p-4 shadow-xs">
            <div className="flex items-center justify-between gap-3">
              <div className="flex items-center gap-2">
                <span className="inline-flex h-3 w-3 rounded-full bg-amber-500" />
                <span className="text-sm font-medium text-[#002C3E]">In review</span>
              </div>
              <button className="rounded-full border border-[#dfe6df] bg-white px-3 py-1.5 text-sm font-medium text-[#002C3E]">
                Review decision
              </button>
            </div>

            <div className="mt-4 space-y-3">
              <button className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#F7444E] hover:bg-[#db3540] px-4 py-3 text-sm font-semibold text-white shadow-xs transition-colors">
                <Check className="h-4 w-4" />
                Approve
              </button>

              <button className="inline-flex w-full items-center justify-center gap-2 rounded-xl border border-[#dfe6df] bg-white px-4 py-3 text-sm font-medium text-[#002C3E] hover:bg-[#f3f7f5] transition-colors">
                <PencilLine className="h-4 w-4 text-[#637981]" />
                Edit
              </button>

              <button className="inline-flex w-full items-center justify-center gap-2 rounded-xl border border-[#dfe6df] bg-white px-4 py-3 text-sm font-medium text-[#002C3E] hover:bg-[#f3f7f5] transition-colors">
                <RotateCcw className="h-4 w-4 text-[#637981]" />
                Regenerate
              </button>
            </div>

            <div className="mt-4 rounded-xl border border-[#dfe6df] bg-[#fbfcf8] p-3">
              <label className="mb-2 block text-sm font-medium text-[#002C3E]">Rejection reason (required)</label>
              <textarea
                defaultValue="Explain what needs to change..."
                className="h-20 w-full resize-none rounded-xl border border-[#dfe6df] bg-[#fbfcf8] p-3 text-sm text-[#002C3E] placeholder-[#637981]/70 outline-none focus:border-[#78BCC4] focus:ring-2 focus:ring-[#78BCC4]/20"
              />
              <button className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-xl border border-rose-300 bg-white px-4 py-3 text-sm font-semibold text-rose-600 hover:bg-rose-50 transition-colors">
                <X className="h-4 w-4" />
                Reject
              </button>
            </div>
          </div>

          <div className="rounded-2xl border border-[#dfe6df] bg-white p-4 shadow-xs">
            <h3 className="text-lg font-bold text-[#002C3E]">Audit timeline</h3>
            <div className="mt-4 space-y-4">
              {[
                ['Generated by AI', '35m ago'],
                ['Moved to draft', '35m ago'],
                ['Queued for review', '35m ago'],
              ].map(([label, time], index) => (
                <div key={label} className="flex items-start gap-3">
                  <div className="mt-0.5 flex h-5 w-5 items-center justify-center rounded-full border border-teal-600 bg-teal-50">
                    <span className="h-2 w-2 rounded-full bg-teal-600" />
                  </div>
                  <div>
                    <p className="text-sm font-medium text-[#002C3E]">{label}</p>
                    <p className="text-xs text-[#637981]">{time}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </aside>
      </div>
    </div>
  );
}
